#!/bin/csh -f

set output = map_LFEs.eps

# Small map
set x1 = -127
set x2 = -121
set y1 = 39
set y2 = 42
set Rop = $x1/$x2/$y1/$y2
set Jop = m-124/40.5/3.5

gmt pscoast -R$Rop -J$Jop -Ba1f0.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y12 -P -K >! $output

#gmt xyz2grd plate_boundary.txt -Gplate_boundary.grd -I0.1 -R$Rop
#gmt grdcontour plate_boundary.grd -A10+f10p -J$Jop -R$Rop -O -K >> $output

# Faults
#gmt psxy fault.xy -R$Rop -J$Jop -Wthin,grey -O -K >> $output

# Tremor
#gmt psxy tremor.txt -R$Rop -J$Jop -Sc0.1 -Ggrey -O -K >> $output

# FAME stations
gmt psxy FAME.txt -R$Rop -J$Jop -St0.3 -Gred -O -K >> $output

# Permanent stations
gmt psxy permanent1.txt -R$Rop -J$Jop -St0.3 -Ggreen -O -K >> $output
gmt psxy permanent3.txt -R$Rop -J$Jop -St0.3 -Gblue -O -K >> $output

# LFEs families from Plourde et al. (2015)
gmt psxy plourde.txt -R$Rop -J$Jop -Sc0.2 -Gblack -O -K >> $output

# First group of LFE families
cat << END >> updown1.dat
-122.43000 40.38000
-122.52000 40.31000
-122.80000 40.48000
END

gmt psxy updown1.dat -R$Rop -J$Jop -St0.5 -Wthick,black -O -K >> $output

# Second group of LFE families
cat << END >> updown2.dat
-122.53000 40.65000
-122.75000 40.75000
-122.85000 40.73000
-122.88000 40.67000
-123.02000 40.69000
END

gmt psxy updown2.dat -R$Rop -J$Jop -Sd0.5 -Wthick,black -O -K >> $output

# Third group of LFE families
cat << END >> updown3.dat
-122.84000 41.02000
-122.85000 41.06000
-122.88000 41.00000
-122.80000 41.05000
-123.17000 41.05000
END

gmt psxy updown3.dat -R$Rop -J$Jop -Sn0.5 -Wthick,black -O -K >> $output

# Families highlighted in the text
# 080401.05.050
cat << END >> family1.dat
-122.87000 40.09000
END

gmt psxy family1.dat -R$Rop -J$Jop -Ss0.5 -Wthick,black -O -K >> $output

# 080413.07.023
cat << END >> family2.dat
-122.77000 40.97000
END

gmt psxy family2.dat -R$Rop -J$Jop -Si0.5 -Wthick,black -O -K >> $output

# 080412.11.038
cat << END >> family3.dat
-122.77000 40.92000
END

gmt psxy family3.dat -R$Rop -J$Jop -Sa0.5 -Wthick,black -O -K >> $output

# 080415.11.008
cat << END >> family4.dat
-122.84000 41.02000
END

gmt psxy family4.dat -R$Rop -J$Jop -Sc0.5 -Wthick,black -O -K >> $output

cat << END >> indices.dat
-122.67000 40.09000 A
-122.23000 40.38000 B
-122.33000 40.65000 C
-122.37000 40.92000 D
-122.57000 40.97000 E
-122.44000 41.02000 F
-122.60000 41.10000 G
END

gmt pstext indices.dat -R$Rop -J$Jop -F+f12p,black -O -K >> $output

# Earthquakes
cat << END >> earthquakes.dat
-125.953 41.292 0.72
-126.574 40.773 0.66
-124.693 40.652 0.65
-124.961 40.412 0.59
-123.497 40.836 0.54
-124.433 40.281 0.50
END

gmt psxy earthquakes.dat -R$Rop -J$Jop -Sa -Gred -O -K >> $output

cat << END >> time_mag.dat
-125.953 41.092 M7.2 2005
-126.574 40.573 M6.6 2005
-124.693 40.852 M6.5 2010
-124.961 40.212 M5.9 2010
-123.497 40.636 M5.4 2008
-124.433 40.081 M5.0 2006
END

gmt pstext time_mag.dat -R$Rop -J$Jop -F+f12p,red -O -K >> $output

# Large map
set x1 = -130
set x2 = -115
set y1 = 35
set y2 = 50
set Rop = $x1/$x2/$y1/$y2
set Jop = m-124/40.5/0.2

gmt pscoast -R$Rop -J$Jop -Ba10f5::wEsN -W0.1p -G255/255/224 -S224/255/255 -Dl -Na -X0.5 -Y0.5 -O -K >> $output

# Location of small map
cat << END >> square.dat
-127 42
-127 39
-121 39
-121 42
-127 42
END

gmt psxy square.dat -R$Rop -J$Jop -Wthicker,red -O -K >> $output

# Cross-section boundaries
set x1 = -127.0
set x2 = -121.0
set y1 = -55.0
set y2 = 5.0
set Rop = $x1/$x2/$y1/$y2
set Jop = x2.72/0.08

# Horizontal line
cat << END >> ground.dat
-127.0 0.0
-121.0 0.0
END

gmt psxy ground.dat -R$Rop -J$Jop -Ba1f0.5:"Longitude":/a20f5:"Depth (km)":WeSn -Wthicker -X-0.6 -Y-7 -O -K >> $output

# Cross-section
gmt psxy plourde_depth.txt -R$Rop -J$Jop -Sc0.2 -Gblack -O >> $output

rm *.dat
