#!/bin/csh -f

set output = map_LFEs.eps

# Small map
set x1 = -127
set x2 = -121
set y1 = 38.1
set y2 = 42.1
set Rop = $x1/$x2/$y1/$y2
set Jop = m-124/40.1/3.5

gmt pscoast -R$Rop -J$Jop -Ba1f0.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y5 -P -K >! $output

# Tremor
#gmt psxy tremor.txt -R$Rop -J$Jop -Sc0.1 -Ggrey -O -K >> $output

# FAME stations
gmt psxy FAME.txt -R$Rop -J$Jop -St0.3 -Gred -O -K >> $output

# Permanent stations
gmt psxy permanent1.txt -R$Rop -J$Jop -St0.3 -Ggreen -O -K >> $output
gmt psxy permanent3.txt -R$Rop -J$Jop -St0.3 -Gblue -O -K >> $output

# LFEs families from Plourde et al. (2015)
gmt psxy plourde.txt -R$Rop -J$Jop -Sc0.2 -Gblack -O -K >> $output

# First group of LFE families
cat << END >> updown1.dat
-122.43000 40.38000
-122.52000 40.31000
-122.80000 40.48000
END

gmt psxy updown1.dat -R$Rop -J$Jop -St0.5 -Wthick,black -O -K >> $output

# Second group of LFE families
cat << END >> updown2.dat
-122.53000 40.65000
-122.75000 40.75000
-122.85000 40.73000
-122.88000 40.67000
-123.02000 40.69000
END

gmt psxy updown2.dat -R$Rop -J$Jop -Sd0.5 -Wthick,black -O -K >> $output

# Families highlighted in the text
# 080401.05.050
cat << END >> family1.dat
-122.87000 40.09000
END

gmt psxy family1.dat -R$Rop -J$Jop -Ss0.5 -Wthick,black -O -K >> $output

# 080413.07.023
cat << END >> family2.dat
-122.77000 40.97000
END

gmt psxy family2.dat -R$Rop -J$Jop -Si0.5 -Wthick,black -O -K >> $output

cat << END >> indices.dat
-122.67000 40.09000 A
-122.57000 40.97000 B
-122.23000 40.38000 C
-122.33000 40.65000 D
END

gmt pstext indices.dat -R$Rop -J$Jop -F+f12p,black -O -K >> $output

# Earthquakes
cat << END >> earthquakes.dat
-125.953 41.292 0.72
-126.574 40.773 0.66
-124.693 40.652 0.65
-124.961 40.412 0.59
-123.497 40.836 0.54
-124.433 40.281 0.50
END

gmt psxy earthquakes.dat -R$Rop -J$Jop -Sa -Gred -O -K >> $output

cat << END >> time_mag.dat
-125.953 41.092 M7.2 2005
-126.574 40.573 M6.6 2005
-124.693 40.852 M6.5 2010
-124.961 40.212 M5.9 2010
-123.497 40.636 M5.4 2008
-124.433 40.081 M5.0 2006
END

gmt pstext time_mag.dat -R$Rop -J$Jop -F+f12p,red -O -K >> $output

# Large map
set x1 = -130
set x2 = -115
set y1 = 35
set y2 = 50
set Rop = $x1/$x2/$y1/$y2
set Jop = m-124/40.1/0.3

gmt pscoast -R$Rop -J$Jop -Ba5f2.5::wEsN -W0.1p -G255/255/224 -S224/255/255 -Dl -Na -X0.5 -Y0.5 -O -K >> $output

# Location of small map
cat << END >> square.dat
-127 42.1
-127 38.1
-121 38.1
-121 42.1
-127 42.1
END

gmt psxy square.dat -R$Rop -J$Jop -Wthicker,red -O >> $output

rm square.dat
rm earthquakes.dat
rm family1.dat
rm family2.dat
rm time_mag.dat
rm updown1.dat
rm updown2.dat
rm indices.dat
